//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.42000
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKHOSTING.Data.Resources {
	using System;
	using System.Reflection;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OKHOSTING.Data.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value must be equal than &apos;{0}&apos;.
		/// </summary>
		public static string OKHOSTING_Data_Validation_CompareValidator_Errors_Equal {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_CompareValidator_Errors_Equal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value must be greater than &apos;{0}&apos;.
		/// </summary>
		public static string OKHOSTING_Data_Validation_CompareValidator_Errors_GreaterThan {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_CompareValidator_Errors_GreaterThan", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value must be greater or equal than &apos;{0}&apos;.
		/// </summary>
		public static string OKHOSTING_Data_Validation_CompareValidator_Errors_GreaterThanEqual {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_CompareValidator_Errors_GreaterThanEqual", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value must be less than &apos;{0}&apos;.
		/// </summary>
		public static string OKHOSTING_Data_Validation_CompareValidator_Errors_LessThan {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_CompareValidator_Errors_LessThan", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value must be less or equal than &apos;{0}&apos;.
		/// </summary>
		public static string OKHOSTING_Data_Validation_CompareValidator_Errors_LessThanEqual {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_CompareValidator_Errors_LessThanEqual", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value must be different than &apos;{0}&apos;.
		/// </summary>
		public static string OKHOSTING_Data_Validation_CompareValidator_Errors_NotEqual {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_CompareValidator_Errors_NotEqual", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value must be between {0} and {1} (inclusive).
		/// </summary>
		public static string OKHOSTING_Data_Validation_RangeValidator_Error {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_RangeValidator_Error", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Value does not mactch regex pattern &apos;{1}&apos;.
		/// </summary>
		public static string OKHOSTING_Data_Validation_RegexValidator_Error {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_RegexValidator_Error", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Object cannot be zero.
		/// </summary>
		public static string OKHOSTING_Data_Validation_RequiredValidator_Errors_Numeric {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_RequiredValidator_Errors_Numeric", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Object cannot be null.
		/// </summary>
		public static string OKHOSTING_Data_Validation_RequiredValidator_Errors_Object {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_RequiredValidator_Errors_Object", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to String cannot be empty.
		/// </summary>
		public static string OKHOSTING_Data_Validation_RequiredValidator_Errors_String {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_RequiredValidator_Errors_String", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to String can&apos;t be an empty string.
		/// </summary>
		public static string OKHOSTING_Data_Validation_StringLengthValidator_Errors_Empty {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_StringLengthValidator_Errors_Empty", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to String length must not be greater than {0}.
		/// </summary>
		public static string OKHOSTING_Data_Validation_StringLengthValidator_Errors_MaxLength {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_StringLengthValidator_Errors_MaxLength", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to String length must be at least {0}.
		/// </summary>
		public static string OKHOSTING_Data_Validation_StringLengthValidator_Errors_MinLength {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_StringLengthValidator_Errors_MinLength", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Type {0} is not equal or a subclass of {1}.
		/// </summary>
		public static string OKHOSTING_Data_Validation_TypeValidator_Error {
			get {
				return ResourceManager.GetString("OKHOSTING_Data_Validation_TypeValidator_Error", resourceCulture);
			}
		}
	}
}
